Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
January 11, 2023 - 10:57:05
Django version 4.1.5, using settings 'todoApp.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Invalid HTTP_HOST header: '52.199.21.169:8000'. You may need to add '52.199.21.169' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '52.199.21.169:8000'. You may need to add '52.199.21.169' to ALLOWED_HOSTS.
Bad Request: /
[11/Jan/2023 10:57:25] "GET / HTTP/1.1" 400 62537
Invalid HTTP_HOST header: '52.199.21.169:8000'. You may need to add '52.199.21.169' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '52.199.21.169:8000'. You may need to add '52.199.21.169' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[11/Jan/2023 10:57:26] "GET /favicon.ico HTTP/1.1" 400 62520
/home/ubuntu/projects/django-todo/todoApp/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
January 11, 2023 - 10:59:19
Django version 4.1.5, using settings 'todoApp.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[11/Jan/2023 10:59:22] "GET / HTTP/1.1" 302 0
[11/Jan/2023 10:59:22] "GET /todos HTTP/1.1" 301 0
[11/Jan/2023 10:59:23] "GET /todos/ HTTP/1.1" 200 3515
[11/Jan/2023 10:59:23] "GET /static/css/style.css HTTP/1.1" 200 225
